# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENCE.txt', 'CNAME']


# Site Settings
title: "GDG Korea DevFair 2014"
email: ""
description: "GDG DevFest is a set of events all around the world"
baseurl: ""
url: "http://devfair2014.gdg.kr"
permalink: "/blog/:title"
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: ""

# Organizer Info
organizerName: "GDG Korea"
organizerAlternateName: "Google Developer Group Korea"
organizerDescription: "구글 기술에 관심이 많은 개발자들의 모임으로 한국에 9개의 지역별, 기술별 모임이 있습니다. 누구에게나 열려있고 열정이 넘치는 개발자들의 모임입니다."
organizerEmail: "gdg.korea@gmail.com"
organizerLogo: "/img/seo/GDG_Korea.png"
organizerLink: "https://plus.google.com/103710008251066466508"

# Head
metaKeywords: "event, gdg, devfair, google, programming, android, chrome, developers, korea"
twitterAccount: "@DevFest"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "http://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/speakers/", text: "Speaker"}
 - {permalink: "/schedule/", text: "schedule"}
 - {permalink: "/team/", text: "Team"}


bottomNavigationLinks:
 #- {link: "http://bit.ly/dfua-c4p", text: "Become a speaker"}
rightNavigationButtons:
 #- {link: "http://bit.ly/dfua-c4p", text: "Become a speaker"}

# Hero Block
heroImage: "fireworks.jpg"
heroTitle: "<typeout> ?"
eventDate: "2014년 11월 29일 토요일 오전 10시 ~ 오후 7시"
typeoutTextValues: '"Android", "Appengine", "Polymer", "Golang", "HTML5", "Dart", "Angularjs", "Chrome"'
typeoutFallback: "Android? Polymer"
heroButtons:
 #- {link: "http://bit.ly/dfua-c4p", text: "Become a speaker"}

# About Block
aboutTitle: "DevFair에서는"
aboutBlock:
 - {title: "Codelab", image: "workshop.jpg", text: "나는 개발자! 궁금했던 기술에 대하여 직접 코드로 배워보는 시간. 여러분의 궁금증을 해소시켜줄 튜터와 함께 액티브한 코딩을 해보며 즐기는 코드랩에 참여해보세요." }
 - {title: "Conference", image: "conference.jpg", text: "GDG에서 엄선한 세션들을 들어보세요. 정말 멋진 발표자분들의 멋진 발표. 듣기만 해도 지식도 쑥쑥, 영감도 쑥쑥!" }
 - {title: "Networking", image: "hackathon.jpg", text: "나와 비슷한 관심사, 공감대를 가진 사람들을 만나보세요. 행사에 참여해 조금만 고개를 돌려보면 모두 같은 생각입니다. 어서 입으로 출력해보세요. '안녕하세요'" }

# Waiting
waitImage: "judges.jpg"
waitTitle: "<span style=\"font-size:80pt;background-color: rgba(0,0,0,0.5);\">\" 忍 \"</span> <h4 style=\"background-color: rgba(0,0,0,0.5);\">기다려주십시요.<h4>"
waitMsg: "참석신청이 곧 시작됩니다."
waitOpen: "코드랩 / 세션 확인 : <a href=\"schedule\">확인하기</a>"
waitSchedule:
 - {msg: "참가 신청 시작" , date: "2014.11.11"}

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "350", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "of pure Google technologies"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
 - {count: "3", specialCharacter: "", info: "parallel tracks", detail: "plus entertainment lounge"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "session_devfest.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "다른 Speaker 보기"

# Location Block
locationBlockTitle: "장소"
eventLocationName: "마루180"
eventLocationLink: "http://cabinet.kinopalace.lviv.ua/showtimes/"
eventStreetAddress: "역삼로 180"
eventAddressLocality: "역삼동"
eventAddressLocalityRegion: "강남구"
eventPostalCode: "79000"
eventAddressCountry: "대한민국"
eventStartTime: "2014-11-29T10:00"
eventDoorTime: "09:00"
eventEndTime: "2014-11-29T19:00"
eventPlaceCoordinates: "37.495472, 127.038854"
mapCenterCoordinates: "37.4953765, 127.0380564"
mapMobileCenterCoordinates: "37.4953765, 127.0380564"

# Venue Block
venueBlockTitle: "공간"
venueBigImage: "maru_0.png"
venueSmallImage1: "maru_1.png"
venueSmallImage2: "maru_2.png"
venueSmallImage3: "maru_3.png"
venueTitle: "마루180"
venueFeatures: ["기술 세미나 진행", "깔끔하고 모던한 실내 인테리어", "스타트업들을 위한 공유 공간"]

venueBigImage1: "mic_0.jpg"
venueSmallImage11: "mic_1.jpg"
venueSmallImage12: "mic_2.jpg"
venueSmallImage13: "mic_3.jpg"
venueTitle1: "마이크임팩트"
venueFeatures1: ["Android Codelab 진행", "카페테리아겸 공유 공간"]
venueOpen1: "block"

venueBigImage2: "maru_0.png"
venueSmallImage21: "maru_1.png"
venueSmallImage22: "maru_2.png"
venueSmallImage23: "maru_3.png"
venueTitle2: "공간.여유.Coffee"
venueFeatures2: ["Tech Codelab 진행","넓은 홀과 작은 회의실", "카페테리아 & 세미나 장소"]
venueOpen2: "none"

venueBigImage3: "maru_0.png"
venueSmallImage31: "maru_1.png"
venueSmallImage32: "maru_2.png"
venueSmallImage33: "maru_3.png"
venueTitle3: "헨델과 그레텔"
venueFeatures3: ["WebTech Codelab 진행", "아기자기하고 귀여운 인테리어", "맛있는 수제 햄버거"]
venueOpen3: "none"

# Tweets Feed Block
tweetsFeedImage: "korean_light.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "devfest"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=900"

# Partners Block
organizersTitle: "주최"
partnersTitle: "후원"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "http://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Early Bird"
  price: "350"
  priceCurrency: "UAH"
  ticketsNumber: "150"
  ribbon: "-5%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-09-30T23:59"
 -
  name: "Last Chance"
  price: "450"
  priceCurrency: "UAH"
  ticketsNumber: "100"
  ribbon: "-20%"
  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-10-01T00:00"
  validThrough: "2014-10-23T23:59"
  disabled: true
 -
  name: "Student"
  price: "200"
  priceCurrency: "UAH"
  ticketsNumber: "50"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-20T10:00"
  validThrough: "2014-10-23T23:59"

# Footer
socialLinks:
 - {link: "https://plus.google.com/103710008251066466508/posts", icon: "google-plus"}
 - {link: "https://facebook.com/gdgkorea", icon: "facebook"}
 #- {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://plus.google.com/103710008251066466508/posts", text: "GDG.Korea"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:gdg.korea@gmail.com", text: "gdg.korea@gmail.com"}
 #-
 # title: "FAQ"
 # links:
#   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "GDG DevFair팀이 요정이란 이야기가 있습니다.<br/>
 24시간 언제 어디에서나 커뮤니티에 기여하는 그들이 사람일리가 없다는 이야기지요. <br/>
다양한 기술 영역에서 능숙 능란하게 다룰 수 있는 사람을 구인하는 것이 말이 안된다는 지적도 있었습니다.<br/>
 혹자는 이들이 구글이 만든 인공지능이나 보스턴 다이나믹이 만든 로봇이 아니냐는 의문을 품었습니다.<br/>
<br/>
 그들은 요정일까요? 인공지능일까요?<br/><br/> 아니면 로봇일까요? <br/>
 GDG DevFair 2014 행사장에서 의문을 풀어주십시요. 의문이 풀리지 않더라도 행사를 위해 고생한 그들에게 박수를 부탁드립니다.<br/>
(요약 : 이번 GDG Devfair 2014 행사를 위해 수고해주신 분들 입니다.)"

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Lviv"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards: 
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   - 
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
